<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Rahul" name="megastores.Forgot_Password" tests="10" failures="1" timestamp="2020-06-12T16:35:29 IST" time="156.189" errors="0">
  <testcase name="existing_email_id" time="0.007" classname="megastores.Forgot_Password">
    <skipped/>
  </testcase> <!-- existing_email_id -->
  <system-out/>
  <testcase name="existing_email_id" time="0.012" classname="megastores.Forgot_Password">
    <failure type="java.lang.AssertionError" message="expected [http://54.147.24.85/megastores/forgot-password] but found [http://54.147.24.85/megastores/]">
      <![CDATA[java.lang.AssertionError: expected [http://54.147.24.85/megastores/forgot-password] but found [http://54.147.24.85/megastores/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at megastores.Forgot_Password.existing_email_id(Forgot_Password.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- existing_email_id -->
  <system-out/>
  <testcase name="existing_email_id" time="20.811" classname="megastores.Forgot_Password">
    <skipped/>
  </testcase> <!-- existing_email_id -->
  <system-out>
Existing Email: Login clicked successfully Existing Email: Forgot Password Link clicked successfully Existing Email: Navigated to OTP screen successfully Test failed: The screen does not consist of title OTP  </system-out>
  <testcase name="existing_email_id" time="0.008" classname="megastores.Forgot_Password">
    <skipped/>
  </testcase> <!-- existing_email_id -->
  <system-out/>
  <testcase name="non_existing_email_id" time="19.323" classname="megastores.Forgot_Password"/>
  <system-out>
Non Existing Email: Login clicked successfully Non Existing Email: Forgot Password Link clicked successfully Test Passed: Non Existing Email: Not redirecting the user to OTP screen if the email does not exist.  </system-out>
  <testcase name="existing_phone_number" time="32.690" classname="megastores.Forgot_Password"/>
  <system-out>
Existing Phone Number: Login clicked successfully Existing Phone Number: Forgot Password Link clicked successfully Existing Phone Number: Navigated to OTP screen successfully Test Passed: Existing Phone Number: Not able to Submit null OTP  </system-out>
  <testcase name="non_existing_phone_number" time="20.278" classname="megastores.Forgot_Password"/>
  <system-out>
Non Existing Phone number: Login clicked successfully Non Existing Phone number: Forgot Password Link clicked successfully Test Passed: Non Existing Phone number: Not redirecting the user to OTP screen if the phone number does not exist.  </system-out>
  <testcase name="existing_user_name" time="28.657" classname="megastores.Forgot_Password"/>
  <system-out>
Existing username: Existing Phone Number: Login clicked successfully Existing username: Existing Phone Number: Forgot Password Link clicked successfully Existing username: Existing Phone Number: Navigated to OTP screen successfully Test Passed: Existing username: Existing Phone Number: Not able to Submit null OTP  </system-out>
  <testcase name="non_existing_username" time="18.376" classname="megastores.Forgot_Password"/>
  <system-out>
Non existing username: Login clicked successfully Non existing username: Forgot Password Link clicked successfully Test Passed: Non existing username: Non Existing Phone number: Not redirecting the user to OTP screen if the phone number does not exist.  </system-out>
  <testcase name="empty_field" time="16.027" classname="megastores.Forgot_Password"/>
  <system-out>
Empty field: Login clicked successfully Empty field: Forgot Password Link clicked successfully Test Passed : Empty field : Not redirecting user to OTP screen if the fields are empty  </system-out>
</testsuite> <!-- megastores.Forgot_Password -->
